# Generated by Django 3.2.2 on 2021-08-08 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('court_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('first_name', models.CharField(db_index=True, max_length=15, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=10, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='D.O.B')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('address', models.TextField(max_length=70, verbose_name='Address')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('photo', models.ImageField(upload_to='images/')),
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('complexion', models.CharField(max_length=15)),
                ('hair_color', models.CharField(max_length=15)),
                ('birth_mark', models.CharField(max_length=30, null=True)),
                ('eye_color', models.CharField(max_length=15)),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMS_API.cell')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CRMS_API.court')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('jail_id', models.AutoField(primary_key=True, serialize=False)),
                ('jail_name', models.CharField(max_length=30)),
                ('jail_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('police_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('punishment_id', models.AutoField(primary_key=True, serialize=False)),
                ('punishment_name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('first_name', models.CharField(db_index=True, max_length=15, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=10, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='D.O.B')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('address', models.TextField(max_length=70, verbose_name='Address')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('photo', models.ImageField(upload_to='images/')),
                ('police_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('post', models.CharField(max_length=10, verbose_name='Post')),
                ('police_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMS_API.policestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_place', models.CharField(max_length=30)),
                ('crime_type', models.CharField(choices=[('MUR', 'Murder'), ('KID', 'Kidnapping'), ('TFT', 'Theft'), ('RAP', 'Rape'), ('ACC', 'Accident'), ('VOL', 'Voilence')], default='TFT', max_length=3)),
                ('crime_dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Crime date and Time')),
                ('fir_dateTime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fir date and Time')),
                ('description', models.CharField(max_length=1000, verbose_name='Crime description')),
                ('victim_name', models.CharField(blank=True, max_length=30, verbose_name='Victim Name')),
                ('reporter_name', models.CharField(max_length=30, verbose_name='Reporter name')),
                ('reporter_photo', models.ImageField(blank=True, upload_to='images/', verbose_name='Reporter Photo')),
                ('repoter_phone_number', models.CharField(max_length=10, verbose_name='Reporter Contact No.')),
                ('fir_status', models.CharField(choices=[('CL', 'Closed'), ('OP', 'Open')], default='OP', max_length=2)),
                ('criminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firOf', to='CRMS_API.criminal')),
                ('punishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CRMS_API.punishment')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='jail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMS_API.jail'),
        ),
        migrations.AddField(
            model_name='cell',
            name='police_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMS_API.policestation'),
        ),
    ]
