# Generated by Django 3.2.2 on 2021-08-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMS_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMS_API.cell'),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='CRMS_API.court'),
        ),
    ]
